server:
  port: 8090
spring:
  rabbitmq:
    host: 47.102.98.244
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 3 #最大重试次数
          initial-interval: 5000 #重试间隔时间（单位毫秒）
        default-requeue-rejected: false #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
  redis:
    host: 47.102.98.244
    port: 6379
    password: Zxq951221
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  trackerList[0]: 172.19.30.196:22122